name: Build Thalixte Reshade 32-bit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
    
    - run: pip install Jinja2
    
    - run: python tools\build.py --platform Win32 --configuration Release
    
    - uses: actions/upload-artifact@v4
      with:
        name: ReShade-Thalixte-x86
        path: bin\Win32\Release\ReShade.dll
